# Copyright (c) 2026 Ritchie Brannan / Morphic Void Limited
# License: MIT (see LICENSE file in repository root)

"""Extract unconditional C++ source lists and shared imports from MSBuild XML.

This is deliberately not an MSBuild evaluator. Compiler settings and target
dependencies belong in CMakeLists.txt; ambiguous source selection is rejected.
"""

import argparse
from pathlib import Path
import xml.etree.ElementTree as ET


NS = "{http://schemas.microsoft.com/developer/msbuild/2003}"


def collect_sources(project, repository):
    repository = Path(repository).resolve()
    sources, projects = [], []
    active = set()

    def resolve_path(value, owner):
        value = value.replace("$(MSBuildThisFileDirectory)", owner.parent.as_posix() + "/")
        value = value.replace("$(ProjectDir)", owner.parent.as_posix() + "/")
        if any(token in value for token in ("$", "%", "*", "?", ";", "\n", "\r", "]==]")):
            raise ValueError(f"{owner}: unsupported source/import path: {value}")
        path = (owner.parent / value.replace("\\", "/")).resolve()
        if not path.is_relative_to(repository):
            raise ValueError(f"{owner}: path escapes repository: {path}")
        if not path.is_file():
            raise ValueError(f"{owner}: missing file: {path}")
        return path

    def visit(path):
        if path in active:
            raise ValueError(f"Cyclic shared import: {path}")
        if path in projects:
            return
        active.add(path)
        projects.append(path)

        def walk(element, conditional=False):
            conditional = conditional or "Condition" in element.attrib
            if element.tag == NS + "ClCompile" and any(
                key in element.attrib for key in ("Include", "Remove", "Update")
            ):
                if conditional or set(element.attrib) != {"Include"} or len(element):
                    raise ValueError(f"{path}: conditional or per-file ClCompile metadata is unsupported")
                source = resolve_path(element.attrib["Include"], path)
                if source not in sources:
                    sources.append(source)
            elif element.tag == NS + "Import":
                imported = element.get("Project", "")
                if element.get("Label") == "Shared" or imported.lower().endswith(".vcxitems"):
                    if conditional:
                        raise ValueError(f"{path}: conditional shared import is unsupported")
                    visit(resolve_path(imported, path))
                elif not (imported.startswith("$(VCTargetsPath)") or
                          imported.startswith("$(UserRootDir)") or
                          imported == "MorphicPolicy.targets"):
                    raise ValueError(f"{path}: unrecognised import requires review: {imported}")
            else:
                for child in element:
                    walk(child, conditional)

        walk(ET.parse(path).getroot())
        active.remove(path)

    visit(resolve_path(str(Path(project).resolve()), repository / "CMakeLists.txt"))
    if not sources:
        raise ValueError(f"{project}: no C++ sources found")
    return sources, projects


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project", type=Path)
    parser.add_argument("--root", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    try:
        sources, projects = collect_sources(args.project, args.root)
        lines = ["# Generated by tools/cmake_sources.py; do not edit."]
        for name, paths in (("VS_SOURCES", sources), ("VS_PROJECTS", projects)):
            lines.append(f"set({name}")
            lines.extend(f"    [==[{path.as_posix()}]==]" for path in paths)
            lines.append(")")
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    except (ValueError, OSError, ET.ParseError) as error:
        parser.exit(1, f"Source manifest error: {error}\n")


if __name__ == "__main__":
    main()
